### ISSUE TITLE
Card does not display vacuum status

### ISSUE THREAD

**Issue by trancefam** [TheLastProject/lovelace-valetudo-map-card#106]
Hello, thank you for the card. I am running into an issue where the vacuum status does not display. I am on the latest version and valetudo 2022.1.0. Here is my config and screenshot of what I see:

```yaml
type: custom:valetudo-map-card
vacuum: valetudo_robot
rotate: 0
crop:
  top: 0
  bottom: 0
  left: 0
  right: 0
min_height: 0.625w
map_scale: 2
show_status: true
show_battery_level: true
show_start_button: true
custom_buttons:
  - text: LR
    service: script.vacuum_living_room
    icon: mdi:sofa
  - text: Kitchen
    service: script.vacuum_kitchen
    icon: mdi:silverware-fork-knife
  - text: BR
    service: script.vacuum_bedroom
    icon: mdi:bed-empty
  - text: Couch
    service: script.vacuum_couch_area
    icon: mdi:table-chair
  - text: Stove
    service: script.vacuum_stove_area
    icon: mdi:stove
```
![image](https://user-images.githubusercontent.com/26947075/147843169-e82c9d72-78e5-4d9c-b6db-3b24a03512c6.png)

I have been experimenting with another custom card called `vacuum-card`. Here is a screenshot of that. I was hoping to see the word `Docked` similar to below:

![image](https://user-images.githubusercontent.com/26947075/147843192-2b260c1e-f0d4-4754-b967-ff28f285a8c2.png)

By debugging in chrome, I can see that the `infoEntity` object looks like: 
![image](https://user-images.githubusercontent.com/26947075/147843299-4f6c63cc-ec04-48a6-8ecf-c96235419562.png)

It seems we should be checking `infoEntity.state` now?
