### ISSUE TITLE
fork valetudo

### ISSUE THREAD

**Issue by foXaCe** [TheLastProject/lovelace-valetudo-map-card#23]
Hello,

it possible to support this fork please ?

https://github.com/rand256/valetudo

**Comment by TheLastProject** [comment]
Possibly, although I would be surprised if it doesn't already just work. If it doesn't, I'm going to have to get a bug report on what is broken and what needs to be changed then. Feel free to reopen if you have more info.

**Comment by foXaCe** [comment]
*************************************************************************
TheLastProject/lovelace-valetudo-map-card
To make Valetudo RE compatible with lovelace-valetudo-map-card project, enable publishMapData option and set map sensor source in HA to topicPrefix/identifier/map_data_parsed (i.e. valetudo/rockrobo/map_data_parsed).
********************************************************************

on the repo ,but I do not understand where I need to make the change

**Comment by TheLastProject** [comment]
Took some searching, but I found what you're saying on https://github.com/rand256/valetudo-mapper but that's a bit weird, as ICantBelieveItsNotValetudo isn't necessary for the normal Valetudo either.

Looking at the code of the fork, I see it still exports the same API. I don't see why it shouldn't just work out of the box with the instructions in my README: https://github.com/TheLastProject/lovelace-valetudo-map-card#configuration

What goes wrong if you just follow my README and ignore everything else?

**Comment by foXaCe** [comment]
Next release for testing RE version, verified on S55 (fw 1898).

The most important change in this release:

Moved map parsing from server-side to clients.

**Comment by TheLastProject** [comment]
Ah, now I see what you mean, they don't send the parsed map anymore: https://github.com/rand256/valetudo/blob/298fa93bfa84d760ac551cc37aad9621aeab3f1f/lib/webserver/WebServer.js#L1064

Okay, in that case, from how I understand it:
1. In https://github.com/rand256/valetudo-mapper, edit `/app/config.json` and change the value `publishMapData` from `false` to `true`
2. Create an MQTT sensor in Home Assistant and save it in `configuration.yaml`:
```
sensor:
  - platform: mqtt
    state_topic: "valetudo/roborock/state"
    json_attributes_topic: "valetudo/roborock/map_data_parsed"
    name: xiaomi_map
    value_template: 'OK'
    scan_interval: 5

recorder:
  exclude:
    entities:
      - sensor.xiaomi_map
```
(This is the same as in the README, but with map_data_parsed instead of map_data)

3. Add my card with the following settings:
```
type: 'custom:valetudo-map-card'
entity: sensor.xiaomi_map
rotate: 0
crop:
  top: 0
  bottom: 0
  left: 0
  right: 0
min_height: 0
```
