### ISSUE TITLE
Rotating does not work without setting degrees

### ISSUE THREAD

**Issue by zvldz** [TheLastProject/lovelace-valetudo-map-card#34]
Rotating does not work without setting degrees(ex: rotate: 1).

Error:
```
Cannot assign to read only property 'rotate' of object '#<Object>'
```
Breaking Changes in 0.106 (Freeze config).
https://github.com/TheLastProject/lovelace-valetudo-map-card/blob/master/valetudo-map-card.js#L239

**Comment by TheLastProject** [comment]
Please update your card, you're using an old version. See #32 and #33.

**Comment by zvldz** [comment]
I'm using the latest version of the card.

**Comment by TheLastProject** [comment]
Still can't reproduce it, works fine for me on 0.106. So my guess is that you're still running an older version (probably just cached in your browser like in #33)

**Comment by zvldz** [comment]
Installed: becff16
Browser cache is cleared.
```
      - type: custom:valetudo-map-card
        entity: sensor.xiaomi_map
        rotate: -1                                                                                                                                                          
        map_scale: 1.5
        crop:
          top: 70
          bottom: 30
          left: 130
          right: 0
        min_height: 0
```
Okay, then I'll just add degrees to the settings.
