### ISSUE TITLE
Cannot assign to read only property 'rotate' of object

### ISSUE THREAD

**Issue by jonnycyborg** [TheLastProject/lovelace-valetudo-map-card#35]
Lovelace card states "Cannot assign to read only property 'rotate' of object '#<Object>'" when setting the rotate value to any number other than 0.

Example config:
```
type: 'custom:valetudo-map-card'
entity: sensor.robovac_map
rotate: 180
crop:
  top: 0
  bottom: 0
  left: 0
  right: 0
min_height: 0
```
Interestingly, `rotate: 3.14rad` works fine.

I believe this started showing up in Home Assistant v0.106.1 which might help either narrow the issue or mean it's not an issue on your end. I'm also not 100% sure if/how the setConfig() function has changed throwing the new error, but would love some help tracking it down.
