### ISSUE TITLE
Add possibility to set cards background color (transparent - to use image as floorplan)

### ISSUE THREAD

**Issue by doemEINS** [TheLastProject/lovelace-valetudo-map-card#43]
Currently it's only possible to set `floor_color` to transparent (`'rgba(0, 0, 0, 0)'`), but to use an image as floorplan in the background, it's necessary to make the actual background of the card itself transparent.

With the lovelace `picture-elements` [card](https://www.home-assistant.io/lovelace/picture-elements/) it's easy to set an image as background that reflects the floorplan. On top of that the lovelace-valetudo-map-card can be added with its customizations
```
type: picture-elements
image: https://online.visual-paradigm.com/repository/images/e5728e49-09ce-4c95-b83c-482deee24386.png
elements:
  - type: 'custom:valetudo-map-card'
    entity: sensor.xiaomi_map
    map_scale: 1.2
    style:
      left: 50%
      top: 50%
    floor_color: 'rgba(0, 0, 0, 0)'
    path_color: 'rgba(255, 0, 0, 1)'
```
It would be great to be able to configure the cards background color.
Thanks for looking into it!
