### ISSUE TITLE
Latest version hangs browser

### ISSUE THREAD

**Issue by jacekpaszkowski** [TheLastProject/lovelace-valetudo-map-card#67]
Hi, after updating to latest version when i click on the view with Valetudo map card whole browser freezes. I've just downgraded to the previous version of card and everyting works ok.
Please help.

I'm running Home Assistant 0.114.0

**Comment by TheLastProject** [comment]
What exact version has issues for you and what exact version works fine?

What is your card config like?

What version of Valetudo are you running?

**Comment by jacekpaszkowski** [comment]
This one works https://www.dropbox.com/s/hphleu0uyvrqdkf/ok_valetudo-map-card.js?dl=0
This casuses browser hangs https://www.dropbox.com/s/tnnlmy0kicxomml/notok_valetudo-map-card.js?dl=0

This is my config:
```yaml
          - crop:
              bottom: 80
              left: 170
              right: 0
              top: 160
            entity: sensor.xiaomi_map_mqtt
            floor_color: '--primary-background-color'
            icon_scale: 0.8
            map_scale: 2
            min_height: 0
            obstacle_strong_color: '--primary-color'
            path_color: '--secondary-text-color'
            rotate: 0
            show_dock: true
            show_path: true
            show_vacuum: true
            type: 'custom:valetudo-map-card'
            vacuum_color: '#CCCC55'
```

There is no difference if i put minimal config from docs.

I'm running Valetudo RE 0.9.7
