### ISSUE TITLE
custom_buttons configuration example

### ISSUE THREAD

**Issue by Apocrathia** [TheLastProject/lovelace-valetudo-map-card#70]
Can we get a configuration example of how the `custom_buttons:` property is supposed to work? I've tried the following and it doesn't appear to have any effect.
```yaml
custom_buttons:
  - start:
      icon: 'mdi:play'
      service: vacuum.start
  - stop:
      icon: 'mdi:stop'
      service: vacuum.stop
```
and also eliminating the key names for each button
```yaml
custom_buttons:
  - icon: 'mdi:play'
    service: vacuum.start
  - icon: 'mdi:stop'
    service: vacuum.stop
```
I will gladly submit a pull request to update the README.md if I can get a solid example of how to implement this.
