### ISSUE TITLE
HA shows "Entity not available" for sensor

### ISSUE THREAD

**Issue by morph027** [TheLastProject/lovelace-valetudo-map-card#75]
Setup:

* Roborock S55 w/ Valetudo 0.6.1
* Home Assistant 0.118.3
* mosquitto 1.6.9-1

MQTT is setup properly as i do have the vacuum sensor which works.

![Screenshot from 2020-12-01 19-57-51](https://user-images.githubusercontent.com/600106/100784481-8a0a0b80-340f-11eb-9832-1d41e71170a6.png)

However, the sensor configured does not show up in the UI.

```yaml
sensor:
  - platform: mqtt
    state_topic: 'valetudo/roborock-s55-1/state'
    json_attributes_topic: 'valetudo/roborock-s55-1/map_data'
    name: sensor.roborock_s55_1_map
    value_template: 'OK'
```

![Screenshot from 2020-12-01 19-54-32](https://user-images.githubusercontent.com/600106/100785097-790dca00-3410-11eb-8c20-aa7d2878f930.png)

The sensor itself does have properties:

![Screenshot from 2020-12-01 20-06-10](https://user-images.githubusercontent.com/600106/100785256-ad818600-3410-11eb-8e8a-69a60e5acfa4.png)
