### ISSUE TITLE
Can't decode payload

### ISSUE THREAD

**Issue by sir-max** [TheLastProject/lovelace-valetudo-map-card#83]
Hi, I am using the latest Valutedo (2021.01.1 - including latest commits as of today). The map card sadly stopped working since I updated the card and Valetudo. I got the following config now (also installed ha_custom_filters):

```
custom_filters:
  - decode_valetudo_map
  - decode_base64_and_inflate
  - unquote
  - urldecode
  - ternary
  - shuffle
  - deflate
  - inflate
  - deflate_and_base64_encode

sensor:
  - platform: mqtt
    state_topic: "valetudo/roborock/state"
    json_attributes_topic: "valetudo/roborock/map_data"
    json_attributes_template: "{% if 'class' in value[1:10] %} {{ value }} {% else %} {{ value | decode_valetudo_map }} {% endif %}"
    name: xiaomi_map
    value_template: 'OK'
```

The issue that pops up is following:

```
Logger: homeassistant.components.mqtt
Source: components/mqtt/__init__.py:983
Integration: MQTT (documentation, issues)
First occurred: 14:23:10 (74 occurrences)
Last logged: 14:27:02

Can't decode payload b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x02\xd0\x00\x0......(hidden encrypted code)......82' on valetudo/roborock/map_data with encoding utf-8 (for <Job HassJobType.Callback <function MqttAttributes._attributes_subscribe_topics.<locals>.attributes_message_received at 0xaeb84418>>)

```
I would appreciate any help since I think this card is very cool and I would like to keep it
