### ISSUE TITLE
camera.map not updating unless browser refresh

### ISSUE THREAD

**Issue by matt8707** [TheLastProject/lovelace-valetudo-map-card#84]
Is there something that has to be done on the user side so that camera.map updates the vacuum position on the map?

lovelace-valetudo-map-card 2021-02-17
Firmware: 2021.02.0 (Valetudo)
home assistant 2021.2.3

```
type: 'custom:valetudo-map-card'
entity: camera.map
rotate: 0
crop:
  top: 0
  bottom: 0
  left: 0
  right: 0
min_height: 0
```
