### ISSUE TITLE
custom_buttons not working, missing 'data'

### ISSUE THREAD

**Issue by bruvv** [TheLastProject/lovelace-valetudo-map-card#97]
When adding a custom button as follows:
```
type: custom:valetudo-map-card
entity: camera.map_data
vacuum_entity: vacuum.valetudo
custom_buttons:
  - service: mqtt.publish
  - service_data:
      topic: /valetudo/robot/GoToLocationCapability/go/set
      payload: ae0ccd4b-b077-4a94-8c54-511441da18aa
```
I get the error:
`Failed to call service mqtt/publish. required key not provided @ data['topic']`
I also tried `data` instead of `service_data` am I doing something wrong?
Also it doesn't matter what kind of icon I use it will always use: `mdi:radiobox-blank`

**Comment by TheLastProject** [comment]
You have a `-` in your yaml too much, so you're creating 2 different list entries.

List entry one:
```
service: mqtt.publish
```

List entry two:
```
service_data:
  topic: /valetudo/robot/GoToLocationCapability/go/set
  payload: ae0ccd4b-b077-4a94-8c54-511441da18aa
```

Remove the second line, so, use this as your YAML:

```
type: custom:valetudo-map-card
entity: camera.map_data
vacuum_entity: vacuum.valetudo
custom_buttons:
  - service: mqtt.publish
    service_data:
     topic: /valetudo/robot/GoToLocationCapability/go/set
     payload: ae0ccd4b-b077-4a94-8c54-511441da18aa
```

**Comment by bruvv** [comment]
Oops that's true. Thanks ! But the icon is still an issue.

**Comment by TheLastProject** [comment]
Works fine for me:

```
custom_buttons:
  - service: mqtt.publish
    icon: mdi:home
    service_data:
      topic: /valetudo/robot/GoToLocationCapability/go/set
      payload: ae0ccd4b-b077-4a94-8c54-511441da18aa
```
